/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Acerca de Nosotros",
      items: [
        {
          type: "autogenerated",
          dirName: "nosotros",
        },
      ],
    },
    {
      type: "category",
      label: "Ética",
      items: [
        {
          type: "autogenerated",
          dirName: "etica",
        },
      ],
    },
    {
      type: "category",
      label: "Plan de Comunicación",
      items: [
        {
          type: "autogenerated",
          dirName: "comunicacion",
        },
      ],
    },
    {
      type: "category",
      label: "WoW",
      items: [
        {
          type: "category",
          label: "Políticas",
          items: [
            {
              type: "autogenerated",
              dirName: "politicas",
            },
          ],
        },
        {
          type: "category",
          label: "Procesos",
          items: [{ type: "autogenerated", dirName: "procesos" }],
        },
        {
          type: "category",
          label: "Estándares",
          items: [
            {
              type: "autogenerated",
              dirName: "estandares",
            },
          ],
        },
        {
          type: "category",
          label: "Manuales",
          items: [
            {
              type: "autogenerated",
              dirName: "manuales",
            },
          ],
        },
        {
          type: "category",
          label: "Plantillas",
          items: [
            {
              type: "autogenerated",
              dirName: "plantillas",
            },
          ],
        },
        {
          type: "category",
          label: "Guías",
          items: [
            {
              type: "autogenerated",
              dirName: "guias",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "SCAMPI",
      items: [
        {
          type: "autogenerated",
          dirName: "scampi",
        },
      ],
    },
    {
      type: "category",
      label: "Zeitgeist",
      items: [
        {
          type: "autogenerated",
          dirName: "zeitgeist",
        },
      ],
    },
    {
      type: "category",
      label: "CR Organizacional",
      items: [{ type: "autogenerated", dirName: "cr" }],
    },
    "FAQs",
  ],
};

export default sidebars;
